### ISSUE TITLE
/jpyx ページへのリンクをサイドナビに配置

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/telescope#133]
@KimuraYu45z 
当初は以下Issueで十分にデバッグやテストしてからという想定だったのですがが、デプロイ後にtelescope側ページでサイドナビにメニューが無いのは正直不便で、デバッグは未完ですが、先に/jpyxページへのリンクをサイドナビに配置した状態で、デプロイしてしまいたいと感じています。

https://github.com/lcnem/telescope/issues/51

問題ないでしょうか？

問題なければ、つのださんか千葉さんに依頼させてもらう作業のひとつにリストアップしておこうと思います。

**Comment by KimuraYu45z** [comment]
なんら問題ありません。

**Comment by YasunoriMATSUOKA** [comment]
@Tomosuke0930 
この件、お願いします。
14時から、neworkで、環境構築等含め、はじめだけ情報共有しながらやってみましょう。

**Comment by Tomosuke0930** [comment]
承知しました。14時からよろしくお願い致します。
