### ISSUE TITLE
monitor DBにない日付の処理の問題

### ISSUE THREAD

**Issue by Senna46** [lcnem/telescope#188]
http://a.test.jpyx.lcnem.net:9000/list?start_year=2021&start_month=10&start_day=1&count=1

上記のように保存されていない過去日付でAPIを叩くと、保存されている最古の報酬データが取られる。

http://a.test.jpyx.lcnem.net:9000/list?start_year=2022&start_month=10&start_day=30&count=1

未来日付については問題なし。

**Comment by YasunoriMATSUOKA** [comment]
UI/UX的な観点では違和感がある現状だったかもしれませんが、最低限の修正は完了済の認識。改めての詳細は未確認ですがクローズします。もし何かあれば、コメントください。
