### ISSUE TITLE
bank sendのtxの成功可否判定に漏れがある

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/telescope#207]
@Senna46 cc: @KimuraYu45z 
以下Issueと同様の問題があると思うので修正対応お願いします。
https://github.com/lcnem/botany/issues/145

**Comment by Senna46** [comment]
projects/main/src/app/models/cosmos/bank.application.service.ts
```
this.bank.send(key, toAddress, amount, privateKey)
```
でtxHashのみ返ってくるようなのですぐに修正は厳しそうです。時間あるときにまた確認します。
