### ISSUE TITLE
ハッシュ値、アドレスの幅が一定に表示されない

### ISSUE THREAD

**Issue by yutaro-elk** [lcnem/telescope#216]
|バージョン| 
|-|
|v0.0.71| 

## 概要
ハッシュ値・アドレスがテーブルなどで複数列表示される時、同じ文字数なのに幅が一定に表示されない

![image](https://user-images.githubusercontent.com/36399275/142573696-327dda5f-0ffe-4b8d-9580-a8fe1fb3beb7.png)

## 再現方法
1. Home ページを表示

## 期待値
等幅フォントで表示し、幅を一定にする

**Comment by YasunoriMATSUOKA** [comment]
修正したのでクローズしておきます。
