### ISSUE TITLE
存在しないdenomをsendできてしまう

### ISSUE THREAD

**Issue by yutaro-elk** [lcnem/telescope#222]
|バージョン| 
|-|
|v0.0.71| 

## 概要
`/cosmos/bank/send` で 存在しないdenomを送信できてしまう。

TxHash: D2B6658E1ED1CBD7306F0DBA46837B5CEDD54FED123180D3D8B98BBC1E99C3E2

![image](https://user-images.githubusercontent.com/36399275/142593101-9065015e-8fa7-4646-b587-83093a472bca.png)

## 再現方法
1. `cosmos/bank/send` に遷移
2. Denomに`sdfsdf`、Amountに1を入力
3. Private Key を入力し 「Send」をクリック

## 期待値
- 存在しないDenomを入力したタイミングでエラーを表示する
- 送信が失敗する

**Comment by KimuraYu45z** [comment]
まっつぁんと言ってた記憶があるのですが、mat-selectにしてやるのもいいかもしれませんね。

**Comment by yutaro-elk** [comment]
フロントのバリデーションは何かしらほしいですね。おっしゃるとおりselectでも良いと思います。
バックエンド的には特に問題ない処理なんでしょうか？

**Comment by YasunoriMATSUOKA** [comment]
ありがとうございます。ご指摘の通り以下2種類の対応が必要かなと思います。

1. HTML上でプルダウンリストにする
2. バックエンドAPI自身はおそらく問題ないのですが、APIリクエストの成功可否判定(bank sendの成功可否判定)の実装は不十分なので、bank.service.tsやbank.application.service.tsの中で適切な成功可否判定やエラーハンドリングの実装を修正する

2については、https://github.com/lcnem/telescope/issues/207 のIssueで上がっていて、過去に類似の修正を加えたことがあるので、既に動いていて、1をこのIssueで対応しておけるとより手堅いという印象を感じました。

**Comment by YasunoriMATSUOKA** [comment]
当初考えていたプルダウンリストで対応するのではなく、残高があるコインのみ、インプットフォームが最初から表示されている状態にして、0のデータは送信処理時に抜いておく形で対応し、問題解決できたと思うのでクローズしておきます。
