### ISSUE TITLE
Confirmのチェックと関係なく送信できる

### ISSUE THREAD

**Issue by yutaro-elk** [lcnem/telescope#223]
|バージョン| 
|-|
|v0.0.71| 

## 概要

Send時にConfirmのチェックボックスに関係なく送信できる。

![Kapture 2021-11-19 at 17 56 19](https://user-images.githubusercontent.com/36399275/142595230-56bff7a8-609a-47ed-80ef-a8dcd93c40ac.gif)

## 再現方法
1. `/cosmos/bank/send` に遷移
2. Confirm チェックボックスをオフのまま送信

## 期待値
- 「Confirmをチェックしてください」などのエラーメッセージを表示する
- Confirm チェックボックス自体を削除する
- Send ボタンをクリック後に確認ダイアログを表示する

**Comment by YasunoriMATSUOKA** [comment]
チェックボックスを廃止する形で修正しました。
