### ISSUE TITLE
同じDenomを複数欄で送信できるが失敗する

### ISSUE THREAD

**Issue by yutaro-elk** [lcnem/telescope#224]
|バージョン| 
|-|
|v0.0.71| 

## 概要
Sendで同じDenomを複数欄で入力後、送信ボタンはクリックし画面も遷移するが失敗する。
ティッカーは「成功」

![Kapture 2021-11-19 at 18 11 05](https://user-images.githubusercontent.com/36399275/142596819-49e469c0-af64-425b-9f60-c6971237f3ee.gif)

## 再現方法
1. `/cosmos/bank/send` に遷移
2.  Denom に `ubtc` Amountに `1` を入力
3. Add ボタンをクリック後再度Denom に `ubtc` Amountに `1` を入力
4. Sendをクリック

## 期待値
- `ubtc`が`2`送信される
- 同じDenomは複数欄入力させない

**Comment by Senna46** [comment]
#225 にてエラーが出るように変更しています。
バックエンド的に同じDenomniのTxを2つ以上はInvalid Coinとして処理できません。

>同じDenomは複数欄入力させない
これをフロントで実装するのが良いかと思っています。

![スクリーンショット 2021-11-22 151047](https://user-images.githubusercontent.com/29295263/142809520-03e08f8d-8f1f-450a-a7c6-f93300e0481e.png)

異なるDemomの場合、
![スクリーンショット 2021-11-22 151159](https://user-images.githubusercontent.com/29295263/142809531-54bc880b-88b5-4f42-9bae-9b65c7521565.png)

**Comment by YasunoriMATSUOKA** [comment]
残高のあるDenomのみ、重複なくDenomは固定値で最初からインプットフォームが表示され、インプットフォームを増やすことはできない実装に修正したため、解決できたと思います。クローズしておきます。
