### ISSUE TITLE
[優先度低]Validator, Delegatorへの報酬が付与されたブロック高さの情報を追加する

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/telescope#82]
@Senna46 
以下URLのような accounts/{{accAddress}} ページで参照できる、Validator, Delegatorへの報酬表示時に、報酬が付与されたブロック高さの情報を併記できるよう実装を追加してほしいという状況です。
http://a.test.jpyx.lcnem.net/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt

@KimuraYu45z 
違和感あればフォロー頂けると助かります。

**Comment by KimuraYu45z** [comment]
> Validator, Delegatorへの報酬表示時に、報酬が付与されたブロック高さの情報を併記

これをそのまま実装に落とし込むのは無理なので、要件をもう少し細分化したほうが良いと思います。

accounts/{{accAddress}}に、block historiesコンテナをつくって、ページング付きでblockごとの情報を表示する、とかは考えられるとは思いますがこれもまだまだ危うい。

あとはblocks/{{blockID}}/accounts/{{accAddress}}ページを作っちゃうというのも暫定候補ですね。

これはAPIで返ってきたJSONを表示するだけの単純作業とは違う(他のはそれでいいんだけど…)ので、いろいろ選択肢が出てきてしまうと思います。

**Comment by YasunoriMATSUOKA** [comment]
すごくざっくりしたイメージとして、以下の表のような表示ができると先方の要求を満たせるのでは？と思っていました。

| blockHeight | amount | denom |
| ----------- | ------ | ----- |
| 1 | 100 | ujsmn |
| ... | ... | ... |

しかし、そのような情報を直接とれるAPIはなく、上記のような表示は現実的ではないと理解しました。

この件の進め方は、Delegator関連の報酬・CDP関連の報酬の表示が実現できた後、このタスクに着手する際に、再度相談させてください。

**Comment by YasunoriMATSUOKA** [comment]
本件、neukind様にて、以下赤枠のようなイメージで、Rewardの履歴を表示したいという状況のようで、それを実現するための技術サポートが必要という状況に見受けられました。

![eth_neukind_dashboard_LI](https://user-images.githubusercontent.com/55148923/127800099-b6d85186-7763-41f8-981c-fd544caec103.jpg)

Validatorとしての報酬と、Delegatorとしての報酬と、CDPによる報酬を分けて表示する必要がないのであれば、大きく分けて、以下の2つの選択肢があるのかなと思っていますが、Validator報酬やDelegator報酬が、。

1. 現時点では直接それら情報を取得できるAPIは存在しないため、現時点で使えるAPIを組み合わせて、`当日残高 - 前日残高 - (当日のトランザクションの入金額合計-当日のトランザクションの出金額合計)` のようなイメージで計算して表示してもらう。
2. 上記のような結果を返すことができる、JPYX専用のAPIエンドポイントを実装し、それを使って表示してもらう。

**Comment by YasunoriMATSUOKA** [comment]
ミスしてクローズしてしまったのでリオープンします

**Comment by KimuraYu45z** [comment]
oopsまだだれも返信してなかったんですね。
@YasunoriMATSUOKA @Senna46 どなたか返信お願いしてもよいでしょうか？

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z cc: @Senna46 
現時点では、直接情報を取得できるAPIはないと思われるため、大筋で以下のような方法を取るしか方法はないという理解であっているでしょうか？

- Validatorとしての報酬, Delegatorとしての報酬, CDPにかかわる報酬それぞれ、現時点までの累積報酬を毎日別途DB等に記録しておき、それらの差分を表示する。

**Comment by KimuraYu45z** [comment]
cdp報酬は別もんとしてほっといてよいかなという気がするのと、おっしゃる通りValidatorとしての報酬, Delegatorとしての報酬、をdbに記録、とかしかないと思いました。

**Comment by Senna46** [comment]
日時を指定して報酬を出すAPIがないので，毎日決まった時間0:00（UTC）にAPIを叩いて情報を取るという感じですかね
今問題にすることではないかもしれませんが，del+valでやると自分で自分に委任した報酬が2重に計算されるのではないかと思います。

**Comment by KimuraYu45z** [comment]
いえ、まっつぁんとneworkでわかったことなんですが、
commision validator reward + delegator reward = total validator rewardなる関係性(0.1+0.9=1.0という関係)があったので、それに気を付けておけば重複計上はせずに済みます。

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z cc: @Senna46 
以下のようなイメージで、validator, delegatorに関する報酬で使用するであろうAPIエンドポイントと、それらの関係(以下の1, 2, 3の報酬について、1の報酬 + 2の報酬 = 3の報酬)について、先方に説明すればいったんOKという感じでしょうか？

APIの参考リンク
https://v1.cosmos.network/rpc/v0.42.6

1. `/cosmos/distribution/v1beta1/delegators/{delegator_address}/rewards` ... DelegationTotalRewards queries the total rewards accrued by a each validator. が現時点までの全Delegator報酬の累積値
2. `/cosmos/distribution/v1beta1/validators/{validator_address}/commission` ... ValidatorCommission queries accumulated commission for a validator. が現時点までの全Validator報酬の累積値
3. `/cosmos/distribution/v1beta1/validators/{validator_address}/outstanding_rewards` ... ValidatorOutstandingRewards queries rewards of a validator address. が1と2の合計値に相当する

**Comment by KimuraYu45z** [comment]
@YasunoriMATSUOKA いったんそれで説明してみましょう。OKかどうかは(先方がどれくらいすんなり理解してくれるかは)おれにもわからないので反応をみてまた判断しましょう。

**Comment by YasunoriMATSUOKA** [comment]
この情報を直接取得可能なAPIが無いことと、
monitorページの一機能として、毎日0時時点での累積報酬額を一覧表的に確認できる機能が実装されたことから、
本Issueは対応不要と判断し、クローズしておきます。
