### ISSUE TITLE
[優先度低] Staking menuでのValidator情報について

### ISSUE THREAD

**Issue by Senna46** [lcnem/telescope#84]
![image](https://user-images.githubusercontent.com/29295263/127094882-c5dc9ef2-1baa-4c8d-a1cd-89336115a572.png)

[staking-memuブレンチ](https://github.com/lcnem/cosmoscan/tree/staking-memu)にてサイドメニューのStakingを再度有効化しました。

一旦エラーなく、Validator情報を表示するところまでは修正しましたが、以下の問題が残っています。

- [x] Consensus Pubkeyが取得できていない
  現状、[object Object]

- [ ] Description がMonikerしか表示できていない。存在しないものはコメントアウトを検討。

以下、未実装のDescription

- [ ] Identity
- [ ] Website
- [ ] Security Contact
- [ ] Details

@KimuraYu45z Stakingメニューは現状は各々のValidator情報を表示するだけのものという認識で大丈夫でしょうか？その他の情報表示や、Validatorへの委任に関する機能追加の必要があればご教示いただけますと幸いです。

**Comment by KimuraYu45z** [comment]
表示系ばっかりやればいいのでトランザクション送信系はまだ放置でいいです。
Consensus Pubkeyに関しては前validator addressでやった方法と同じやり方でunpackCosmosAnyからごにょごにょやればよい。

**Comment by KimuraYu45z** [comment]
サイドメニューの「staking」で飛んだ先は

- stakingモジュールのパラメータ等の一般的情報の表示
- stakingモジュールのトランザクションの送信ページへのnav-list

の表示で多分十分です

**Comment by KimuraYu45z** [comment]
スクショのはvalidators/:validator_idのページ。

**Comment by KimuraYu45z** [comment]
`validators/:validator_id`は多分すでにほとんどできているので手直しでよい。

**Comment by Senna46** [comment]
- [ ] stakingモジュールのパラメータ等の一般的情報の表示
こちらは現状で一旦完了

- [ ] stakingモジュールのトランザクションの送信ページへのnav-list
該当ページがわからないので着手してません。

**Comment by KimuraYu45z** [comment]
いやパラメータ等が表示できてるわけではないかと。

**Comment by KimuraYu45z** [comment]
validator表示画面が完了しただけの状態

**Comment by KimuraYu45z** [comment]
tx送信ページとしては`projects/cosmoscan/src/app/cosmos/staking/delegators/create`がある

**Comment by Senna46** [comment]
パラメータとは各Validatorのアーニングスとかという認識で大丈夫ですか？

**Comment by KimuraYu45z** [comment]
違いますgenesis.jsonに書かれてたやつがパラメータです
stakingにparams取得APIがあるはず

**Comment by Senna46** [comment]
わかりました、どういったものがパラメータに含まれているのか、すぐに具体的なものが浮かばなかったのでAPI見ておきます。
ありがとうございます。

**Comment by YasunoriMATSUOKA** [comment]
このIssueが意図していたところはもはやよくわからなくなったと思うのでクローズしておきます。
